name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Say Hello Mona it is ${{ env.DAY_OF_WEEK }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! Oh yeah, and Zach says $MAKING_THIS_UP"
        env:
          First_Name: Mona
          DAY_OF_WEEK: Tuesday
          MAKING_THIS_UP: ${{ vars.MAKING_THIS_UP_A }}
